exec-once = hyprctl setcursor Bibata-Modern-Classic 24
exec-once = sh -c 'waybar &'
exec-once = awww-daemon
exec-once = awww img /home/jperalta/Pictures/Wallpapers/tokyonight_original.png --transition-type none
